micronaut:
  application:
    name: pg-cdt
datasources:
  default:
    driverClassName: com.impossibl.postgres.jdbc.PGDriver
    url: ${DEV_DATABASE_URL:`jdbc:pgsql://localhost/pg_cdt`}
    username: ${DEV_DATABASE_USERNAME:postgres}
    password: ${DEV_DATABASE_PASSWORD:''}
liquibase:
  datasources:
    default:
      change-log: 'classpath:changelog.xml'
      default-schema: public